gmf:
 user_count: 1024
 item_count: 2048
 gmf_dim: 8
 
mlp:
 user_count: 1024
 item_count: 2048
 mlp_dim: 32
 layers_count: 3
 slope: 0.2
 dropout: 0.1
 user_features: 0
 item_features: 0

neu_mf:
 user_count: 1024
 item_count: 2048
 mlp_dim: 32
 layers_count: 3
 slope: 0.2
 dropout: 0.1
 user_features: 0
 item_features: 0
 gmf_dim: 8
 alpha: 0.5