user_count: 1024
item_count: 2048

gmf:
 gmf_dim: 8
 
mlp:
 mlp_dim: 32
 layers_count: 3
 slope: 0.2
 dropout: 0.1
 user_features: 0
 item_features: 0

neu_mf:
 mlp_dim: 32
 layers_count: 3
 slope: 0.2
 dropout: 0.1
 user_features: 0
 item_features: 0
 gmf_dim: 8
 alpha: 0.5
 
dataset:
 negatives_per_user: 1